import { vi } from 'vitest';
import type { IApiClient } from '@/api/client';

/**
 * Construye un doble de `IApiClient` con todos los métodos del contrato.
 *
 * Fábrica compartida para las pruebas de servicios: evita duplicar el
 * contrato en cada archivo de test (DRY) y previene la deriva cuando se
 * añaden métodos nuevos al puerto (regla CLAUDE: un único punto de verdad).
 */
export function makeApiClientMock(): IApiClient {
  return {
    health: vi.fn(),
    listTenants: vi.fn(),
    createTenant: vi.fn(),
    updateTenant: vi.fn(),
    deleteTenant: vi.fn(),
    listLandings: vi.fn(),
    getLanding: vi.fn(),
    createLanding: vi.fn(),
    updateLanding: vi.fn(),
    deleteLanding: vi.fn(),
    publishLanding: vi.fn(),
    compileLanding: vi.fn(),
    generateLanding: vi.fn(),
    // Páginas del Portal del Cliente (configurador único landing/portal) — espejo del contrato IApiClient.
    listPortalPages: vi.fn(),
    getPortalPage: vi.fn(),
    createPortalPage: vi.fn(),
    updatePortalPage: vi.fn(),
    deletePortalPage: vi.fn(),
    publishPortalPage: vi.fn(),
    generatePortalPage: vi.fn(),
    generateSchema: vi.fn(),
    listSchemas: vi.fn(),
    validateSchema: vi.fn(),
    listSchemaVersions: vi.fn(),
    createSchemaVersion: vi.fn(),
    createCheckout: vi.fn(),
    confirmCheckout: vi.fn(),
    captureLead: vi.fn(),
    getLeadAttribution: vi.fn(),
    generateQuote: vi.fn(),
    scheduleAppointment: vi.fn(),
    listMarketplaceTemplates: vi.fn(),
    createMarketplaceTemplate: vi.fn(),
    importMarketplaceTemplate: vi.fn(),
    recordAnalyticsEvent: vi.fn(),
    getAnalyticsDashboard: vi.fn(),
    deployToCdn: vi.fn(),
    getTenantAppearance: vi.fn(),
    upsertTenantAppearance: vi.fn(),
    // Rebranding por URL (Fase 5) — espejo del contrato IApiClient.
    extractUrlStyles: vi.fn(),
    listRebrandingConfigs: vi.fn(),
    createRebrandingConfig: vi.fn(),
    deleteRebrandingConfig: vi.fn(),
    listContentItems: vi.fn(),
    createContentItem: vi.fn(),
    getContentItem: vi.fn(),
    updateContentItem: vi.fn(),
    deleteContentItem: vi.fn(),
    ingestDocumentFile: vi.fn(),
    ingestDocumentUrl: vi.fn(),
    listDocuments: vi.fn(),
    searchDocuments: vi.fn(),
    getDocument: vi.fn(),
    deleteDocument: vi.fn(),
    listSynonyms: vi.fn(),
    createSynonym: vi.fn(),
    updateSynonym: vi.fn(),
    deleteSynonym: vi.fn(),
    importSynonyms: vi.fn(),
    exportSynonyms: vi.fn(),
    listKeywords: vi.fn(),
    createKeyword: vi.fn(),
    updateKeyword: vi.fn(),
    deleteKeyword: vi.fn(),
    listCatalogItems: vi.fn(),
    createCatalogItem: vi.fn(),
    getCatalogItem: vi.fn(),
    updateCatalogItem: vi.fn(),
    deleteCatalogItem: vi.fn(),
    listChannels: vi.fn(),
    createChannel: vi.fn(),
    getChannel: vi.fn(),
    updateChannel: vi.fn(),
    deleteChannel: vi.fn(),
    listConversations: vi.fn(),
    listConversationMessages: vi.fn(),
    sendConversationMessage: vi.fn(),
    listBotProviders: vi.fn(),
    upsertBotProvider: vi.fn(),
    deleteBotProvider: vi.fn(),
    getBotQueueStats: vi.fn(),
    getBotQuotaUsage: vi.fn(),
    testRouter: vi.fn(),
    // Operación del bot (Bloque B) — espejo del contrato IApiClient.
    listContacts: vi.fn(),
    createContact: vi.fn(),
    getContact: vi.fn(),
    updateContact: vi.fn(),
    deleteContact: vi.fn(),
    listTemplates: vi.fn(),
    createTemplate: vi.fn(),
    getTemplate: vi.fn(),
    updateTemplate: vi.fn(),
    deleteTemplate: vi.fn(),
    listNavigationTrees: vi.fn(),
    createNavigationTree: vi.fn(),
    getNavigationTree: vi.fn(),
    updateNavigationTree: vi.fn(),
    deleteNavigationTree: vi.fn(),
    listCampaigns: vi.fn(),
    createCampaign: vi.fn(),
    getCampaign: vi.fn(),
    updateCampaign: vi.fn(),
    deleteCampaign: vi.fn(),
    addCampaignRecipient: vi.fn(),
    listCampaignRecipients: vi.fn(),
    updateCampaignRecipient: vi.fn(),
    dispatchCampaign: vi.fn(),
    sendIndividualMessage: vi.fn(),
    importContactsCsv: vi.fn(),
    importCampaignRecipientsCsv: vi.fn(),
    uploadRecipientFile: vi.fn(),
    listRecipientFiles: vi.fn(),
    previewRecipientFile: vi.fn(),
    dispatchCampaignFromFile: vi.fn(),
    listInterventions: vi.fn(),
    createIntervention: vi.fn(),
    getIntervention: vi.fn(),
    updateIntervention: vi.fn(),
    getInterventionsPendingCount: vi.fn(),
    assignIntervention: vi.fn(),
    listInterventionMessages: vi.fn(),
    replyIntervention: vi.fn(),
    closeIntervention: vi.fn(),
    getMaintenanceConfig: vi.fn(),
    upsertMaintenanceConfig: vi.fn(),
    getOperationsStatsOverview: vi.fn(),
    purgeMaintenance: vi.fn(),
    optimizeMaintenance: vi.fn(),
    listActiveConversations: vi.fn(),
    createBackup: vi.fn(),
    restoreBackup: vi.fn(),
    getTableStats: vi.fn(),
    runScheduledMaintenance: vi.fn(),
    // Captación publicitaria (C-1, eslabón ①) — espejo del contrato IApiClient.
    listAdCampaigns: vi.fn(),
    createAdCampaign: vi.fn(),
    getAdCampaign: vi.fn(),
    updateAdCampaign: vi.fn(),
    deleteAdCampaign: vi.fn(),
    // Dominios personalizados (PSEO hosts) — espejo del contrato IApiClient.
    listPseoHosts: vi.fn(),
    requestPseoHost: vi.fn(),
    verifyPseoHost: vi.fn(),
    deletePseoHost: vi.fn(),
    // CRM (Ventas, P3) — espejo del contrato IApiClient.
    listStages: vi.fn(),
    createStage: vi.fn(),
    getStage: vi.fn(),
    updateStage: vi.fn(),
    deleteStage: vi.fn(),
    listDeals: vi.fn(),
    createDeal: vi.fn(),
    getDeal: vi.fn(),
    updateDeal: vi.fn(),
    deleteDeal: vi.fn(),
    listDealHistory: vi.fn(),
    listDealTasks: vi.fn(),
    createDealTask: vi.fn(),
    listTasks: vi.fn(),
    createTask: vi.fn(),
    getTask: vi.fn(),
    updateTask: vi.fn(),
    deleteTask: vi.fn(),
    listSla: vi.fn(),
    upsertSla: vi.fn(),
    getFunnel: vi.fn(),
    getCrmSummary: vi.fn(),
    // Autenticación de estudio (RBAC) — espejo del contrato IApiClient.
    login: vi.fn(),
    logout: vi.fn(),
    getMe: vi.fn(),
    getMyMemberships: vi.fn(),
    changePassword: vi.fn(),
    updateMe: vi.fn(),
    // Usuarios de plataforma (control plane, super-admin).
    listUsers: vi.fn(),
    createUser: vi.fn(),
    updateUser: vi.fn(),
    deleteUser: vi.fn(),
    listUserMemberships: vi.fn(),
    addUserMembership: vi.fn(),
    deleteUserMembership: vi.fn(),
    // Miembros por tenant (RBAC, admin).
    listMembers: vi.fn(),
    addMember: vi.fn(),
    updateMember: vi.fn(),
    removeMember: vi.fn(),
  };
}
